#!/usr/bin/env python3
"""Turn Harbour's help articles (one markdown file per article and language) into what loads them.

The markdown under content/help/<language>/ is the source. This writes two things from it:

  data/help/*.json                   what `osy import` loads into a running desk: the categories and sections (with their
                                     Swedish and Arabic names), the articles, and every language's version as a draft.
  tests/help-articles.test.osy       the same rows, written by the test's fixture (the block between the GENERATED
                                     markers), because `osy test` never imports.

Run it after editing an article:      python3 content/help/build.py
Check nothing is stale (exit 1 if so): python3 content/help/build.py --check
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
APP = HERE.parent.parent
DATA = APP / "data" / "help"
TEST = APP / "tests" / "help-articles.test.osy"
LANGUAGES = ["en", "sv", "ar"]          # the original first
BEGIN = "// ── BEGIN GENERATED by content/help/build.py — edit the markdown, then run it ──"
END = "// ── END GENERATED ──"


def front_matter(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        sys.exit(f"{path}: no front-matter (a --- block at the top)")
    meta = {}
    for line in m.group(1).splitlines():
        if not line.strip():
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1]
        meta[key.strip()] = value
    body = m.group(2).strip() + "\n"
    return meta, body


def load():
    shelves = json.loads((HERE / "shelves.json").read_text(encoding="utf-8"))
    sections = {s["slug"]: (c, s) for c in shelves for s in c["sections"]}
    articles = []
    for path in sorted((HERE / "en").glob("*.md")):
        meta, body = front_matter(path)
        for key in ("slug", "title", "summary", "category", "section", "audience", "position", "version"):
            if key not in meta:
                sys.exit(f"{path}: front-matter has no '{key}:'")
        if meta["slug"] != path.stem:
            sys.exit(f"{path}: slug '{meta['slug']}' is not the file's name")
        if meta["section"] not in sections:
            sys.exit(f"{path}: section '{meta['section']}' is not in shelves.json")
        if sections[meta["section"]][0]["slug"] != meta["category"]:
            sys.exit(f"{path}: section '{meta['section']}' is not in category '{meta['category']}'")
        if meta["audience"] != "Everyone":
            sys.exit(f"{path}: audience must be Everyone — these are the public help centre's articles")
        versions = {"en": (meta, body)}
        for lang in LANGUAGES[1:]:
            other = HERE / lang / path.name
            if not other.exists():
                sys.exit(f"{other}: missing — every article is written in {', '.join(LANGUAGES)}")
            ometa, obody = front_matter(other)
            for key in ("slug", "title", "summary", "version"):
                if key not in ometa:
                    sys.exit(f"{other}: front-matter has no '{key}:'")
            if ometa["slug"] != meta["slug"]:
                sys.exit(f"{other}: slug '{ometa['slug']}' differs from the English '{meta['slug']}'")
            versions[lang] = (ometa, obody)
        articles.append((meta, versions))
    for lang in LANGUAGES[1:]:
        for other in (HERE / lang).glob("*.md"):
            if not (HERE / "en" / other.name).exists():
                sys.exit(f"{other}: no English original")
    articles.sort(key=lambda a: (a[0]["section"], int(a[0]["position"])))
    return shelves, articles


def envelope(entity, key, rows, lookups=None, language=None):
    e = {"entity": entity, "key": key}
    if language:
        e["language"] = language
    if lookups:
        e["lookups"] = lookups
    e["rows"] = rows
    return json.dumps(e, ensure_ascii=False, indent=2) + "\n"


def data_files(shelves, articles):
    files = {}
    files["01-categories.json"] = envelope("KnowledgeCategory", "Slug", [
        {"Slug": c["slug"], "Name": c["name"]["en"], "Description": c["description"]["en"], "Position": c["position"],
         "Audience": "Everyone"} for c in shelves])
    n = 2
    for lang in LANGUAGES[1:]:
        files[f"0{n}-categories.{lang}.json"] = envelope("KnowledgeCategory", "Slug", [
            {"Slug": c["slug"], "Name": c["name"][lang], "Description": c["description"][lang]} for c in shelves],
            language=lang)
        n += 1
    files[f"0{n}-sections.json"] = envelope("KnowledgeSection", "Slug", [
        {"Slug": s["slug"], "Category": c["slug"], "Name": s["name"]["en"], "Position": s["position"]}
        for c in shelves for s in c["sections"]], lookups={"Category": "KnowledgeCategory[Slug]"})
    n += 1
    for lang in LANGUAGES[1:]:
        files[f"0{n}-sections.{lang}.json"] = envelope("KnowledgeSection", "Slug", [
            {"Slug": s["slug"], "Name": s["name"][lang]} for c in shelves for s in c["sections"]], language=lang)
        n += 1
    files[f"0{n}-articles.json"] = envelope("KnowledgeArticle", "Slug", [
        {"Slug": m["slug"], "Section": m["section"], "Language": "en", "Audience": m["audience"],
         "Position": int(m["position"])} for m, _ in articles], lookups={"Section": "KnowledgeSection[Slug]"})
    n += 1
    files[f"0{n}-versions.json"] = envelope("KnowledgeRevision", ["Article", "Language", "Number"], [
        {"Article": m["slug"], "Language": lang, "Number": int(vm["version"]), "Title": vm["title"],
         "Summary": vm["summary"], "Body": body}
        for m, versions in articles for lang in LANGUAGES for vm, body in [versions[lang]]],
        lookups={"Article": "KnowledgeArticle[Slug]"})
    return files


def osy(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def test_block(shelves, articles):
    out = [BEGIN,
           "/// The rows `osy import` writes from data/help/ — the categories and sections in three languages, the ten",
           "/// articles, and each article's English, Swedish and Arabic version as a draft. Run as somebody who manages",
           "/// the knowledge base, as the import is.",
           "void ImportHelpArticles() {"]
    for c in shelves:
        out.append(f"  var c_{c['slug'].replace('-', '_')} = new KnowledgeCategory {{ Slug = {osy(c['slug'])}, "
                   f"Name = {osy(c['name']['en'])}, Description = {osy(c['description']['en'])}, "
                   f"Position = {c['position']} }};")
    for c in shelves:
        for s in c["sections"]:
            out.append(f"  var s_{s['slug'].replace('-', '_')} = new KnowledgeSection {{ Category = "
                       f"c_{c['slug'].replace('-', '_')}, Slug = {osy(s['slug'])}, Name = {osy(s['name']['en'])}, "
                       f"Position = {s['position']} }};")
    out.append("  UnitOfWork.Commit();")
    for lang in LANGUAGES[1:]:
        out.append(f"  Session.SetLanguage({osy(lang)});")
        for c in shelves:
            v = f"c_{c['slug'].replace('-', '_')}"
            out.append(f"  {v}.Name = {osy(c['name'][lang])}; {v}.Description = {osy(c['description'][lang])};")
        for c in shelves:
            for s in c["sections"]:
                out.append(f"  s_{s['slug'].replace('-', '_')}.Name = {osy(s['name'][lang])};")
        out.append("  UnitOfWork.Commit();")
    out.append(f"  Session.SetLanguage({osy(LANGUAGES[0])});")
    for m, versions in articles:
        a = f"a_{m['slug'].replace('-', '_')}"
        out.append(f"  var {a} = new KnowledgeArticle {{ Section = s_{m['section'].replace('-', '_')}, "
                   f"Slug = {osy(m['slug'])}, Language = \"en\", Position = {int(m['position'])} }};")
        for lang in LANGUAGES:
            vm, body = versions[lang]
            out.append(f"  new KnowledgeRevision {{ Article = {a}, Language = {osy(lang)}, Number = {int(vm['version'])},")
            out.append(f"    Title = {osy(vm['title'])}, Summary = {osy(vm['summary'])},")
            out.append(f"    Body = {osy(body)} }};")
    out.append("  UnitOfWork.Commit();")
    out.append("}")
    out.append("")
    out.append("/// Every article's address, in the order the import writes them.")
    out.append("List<string> HelpArticleSlugs() {")
    out.append("  return [" + ", ".join(osy(m["slug"]) for m, _ in articles) + "];")
    out.append("}")
    out.append(END)
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    shelves, articles = load()
    stale = []
    for name, text in data_files(shelves, articles).items():
        path = DATA / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(str(path.relative_to(APP)))
            if not check:
                DATA.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    test = TEST.read_text(encoding="utf-8")
    if BEGIN not in test or END not in test:
        sys.exit(f"{TEST}: no GENERATED markers")
    head, rest = test.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + test_block(shelves, articles) + tail
    if new != test:
        stale.append(str(TEST.relative_to(APP)))
        if not check:
            TEST.write_text(new, encoding="utf-8")
    if check:
        if stale:
            print("stale — run python3 content/help/build.py:\n  " + "\n  ".join(stale))
            sys.exit(1)
        print(f"up to date: {len(articles)} articles in {', '.join(LANGUAGES)}")
    else:
        print(f"{len(articles)} articles in {', '.join(LANGUAGES)}; wrote " + (", ".join(stale) or "nothing (up to date)"))


if __name__ == "__main__":
    main()
